---
- name: client-install-pre | Initialize skip_install to false
  set_fact:
    skip_install: false

      
- name: client-install-pre | Check if inventory.xml exists
  stat:
    path: "{{ observer_oracle_inventory }}/ContentsXML/inventory.xml"
  register: inventory_xml_stat
  failed_when: false  # Prevent failure if the file doesn't exist

- name: client-install-pre | Check if oracle_home exists in inventory.xml
  slurp:
    src: "{{ observer_oracle_inventory }}/ContentsXML/inventory.xml"
  register: inventory_xml
  failed_when: false  # Prevent failure if the file doesn't exist
  when: inventory_xml_stat.stat.exists

- name: client-install-pre | Decode inventory.xml content
  set_fact:
    inventory_xml_content: "{{ inventory_xml.content | b64decode }}"
  when: inventory_xml_stat.stat.exists

- name: client-install-pre | Check if oracle home exists in inventory.xml
  set_fact:
    observer_oracle_home_exists: "{{ inventory_xml_content is search(oracle_home) }}"
  when: inventory_xml_stat.stat.exists  # Only set if inventory.xml exists
  failed_when: false  # Prevent failure if the file doesn't exist

- name: client-install-pre | Set global fact to stop play if Oracle Home exists
  set_fact:
    skip_install: true
  when: 
    - (observer_oracle_home_exists is defined and observer_oracle_home_exists) 
  

- name: client-install-pre | Show skip status for host
  debug:
    msg: "Skipping installation on this host: {{ inventory_hostname }}"
  when: skip_install
  